/**
 * Mock LLM provider — canned interviewer behavior with zero API calls.
 *
 * Purpose: develop and test the app (UI, streaming, voice mode, reports)
 * without burning provider quota. Set LLM_PROVIDER=mock to activate.
 *
 * It follows the same contract as real providers and respects the engine's
 * director notes: when the note asks for a wrap-up, it emits the end token.
 */

const QUESTIONS = [
  "To start us off, could you walk me through a recent project you're proud of, and what your specific contribution was?",
  "Interesting — what was the hardest technical decision you had to make there, and how did you weigh the trade-offs?",
  "Let's go deeper. If that system suddenly had ten times the traffic, what would break first, and how would you address it?",
  "Tell me about a time something you shipped went wrong in production. How did you find out, and what did you do?",
  "One more from me — how do you decide when code is good enough to ship versus when it needs another pass?",
];

const ACKS = [
  "That makes sense, thanks for laying it out so clearly.",
  "Got it — I like how you framed the trade-offs there.",
  "Okay, that's a reasonable approach.",
  "Thanks, that gives me a good picture.",
];

const WRAP_UP =
  "Thanks so much for walking me through your experience today — this was a great conversation. The team will review everything and be in touch about next steps. Have a great rest of your day! <<END_INTERVIEW>>";

export class MockProvider {
  constructor({ delayMs = 25 } = {}) {
    this.delayMs = delayMs;
    this.name = "mock";
  }

  #pickReply(messages) {
    const text = messages.map((m) => m.content).join("\n");
    const wantsWrap = /wrap up|final question|conclude the interview/i.test(text);
    const answers = messages.filter((m) => m.role === "user").length - 1; // minus primer
    if (wantsWrap) return WRAP_UP;
    if (answers <= 0) {
      return `Hi, I'm Morgan — thanks for joining today. We'll keep this conversational. ${QUESTIONS[0]}`;
    }
    const ack = ACKS[answers % ACKS.length];
    const q = QUESTIONS[Math.min(answers, QUESTIONS.length - 1)];
    return `${ack} ${q}`;
  }

  /** @param {import("./provider.js").ChatRequest} req */
  async *streamChat(req) {
    const reply = this.#pickReply(req.messages);
    for (const word of reply.split(/(?<=\s)/)) {
      await new Promise((r) => setTimeout(r, this.delayMs));
      yield word;
    }
  }

  /** @param {import("./provider.js").ChatRequest} _req */
  async generateJSON(_req) {
    return {
      summary:
        "Mock evaluation: the candidate engaged with every question and communicated clearly. (Generated by the mock provider — switch LLM_PROVIDER back to a real model for genuine evaluation.)",
      scores: {
        technical_competency: 4,
        communication: 4,
        problem_solving: 3,
        experience_ownership: 4,
        culture_collaboration: 3,
      },
      overallScore: 4,
      recommendation: "hire",
      strengths: [
        "Answered every question directly and stayed on topic.",
        "Clear structure in responses.",
        "Comfortable discussing trade-offs.",
      ],
      concerns: ["This is a mock report — no real evaluation was performed."],
      questionHighlights: [
        {
          topic: "Recent project",
          assessment: "Mock assessment of the candidate's project discussion.",
        },
      ],
      followUpSuggestions: ["Re-run this interview with a real LLM provider."],
    };
  }
}
